version: '2'
services:
  postgres:
    image: r.qihoo.cloud/library/postgres:9.6.1
    container_name: airflow-local-postgres-${DEV_USER}
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - default
  webserver:
    image: puckel/docker-airflow:1.8.2-ts
    container_name: airflow-local-server-${DEV_USER}
    restart: always
    depends_on:
        - postgres
    environment:
        # - LOAD_EX=n
        - EXECUTOR=Local
    volumes:
        - ./dags:/usr/local/airflow/dags
        - ./requirements.txt:/requirements.txt
    ports:
        - "${DEV_PORT}:8080"
    command: webserver
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
