FROM puckel/docker-airflow:1.8.2 

COPY ./requirements.basic.txt /tmp/requirements.txt
RUN pip install --index https://pypi.mirrors.ustc.edu.cn/simple/ --user -r /tmp/requirements.txt
COPY ./requirements.tushare.txt /tmp/requirements.txt
RUN pip install --index https://pypi.mirrors.ustc.edu.cn/simple/ --user -r /tmp/requirements.txt
